# Generated by Django 5.2.11 on 2026-03-02 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pim', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WPSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField()),
                ('consumer_key', models.CharField(max_length=255)),
                ('consumer_secret', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wp_sites', to='sites.distributor')),
            ],
            options={
                'verbose_name': 'WordPress Site',
            },
        ),
        migrations.CreateModel(
            name='WPProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_product_id', models.IntegerField()),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('master_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pim.mastersku')),
                ('wp_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='wp_sync.wpsite')),
            ],
            options={
                'unique_together': {('wp_site', 'master_sku')},
            },
        ),
    ]
