# Generated by Django 5.2.11 on 2026-03-02 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0003_seed_categories'),
        ('wp_sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wpproductmapping',
            options={'verbose_name': 'WP Product Mapping', 'verbose_name_plural': 'WP Product Mappings'},
        ),
        migrations.AlterUniqueTogether(
            name='wpproductmapping',
            unique_together={('master_sku', 'wp_site')},
        ),
        migrations.AddField(
            model_name='wpproductmapping',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wpproductmapping',
            name='sync_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wpproductmapping',
            name='sync_status',
            field=models.CharField(choices=[('pending', '待同步'), ('syncing', '同步中'), ('synced', '已同步'), ('failed', '同步失败'), ('draft', 'WP已下架')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='wpproductmapping',
            name='wp_sku',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wpproductmapping',
            name='master_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wp_mappings', to='pim.mastersku'),
        ),
        migrations.AlterField(
            model_name='wpproductmapping',
            name='wp_product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='wpproductmapping',
            name='last_synced',
        ),
    ]
