# Generated by Django 5.2.11 on 2026-03-02 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_code', models.CharField(max_length=50, unique=True)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master SKU',
                'verbose_name_plural': 'Master SKUs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code_prefix', models.CharField(max_length=20)),
                ('settlement_cycle', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('circuit_breaker', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=10, help_text='Lower number = higher priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='SupplierSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(max_length=100)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_status', models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=20)),
                ('last_stock_check', models.DateTimeField(blank=True, null=True)),
                ('master_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_skus', to='pim.mastersku')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_skus', to='pim.supplier')),
            ],
            options={
                'verbose_name': 'Supplier SKU',
                'unique_together': {('supplier', 'master_sku')},
            },
        ),
    ]
