# Generated by Django 5.2.11 on 2026-03-02 12:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_zh', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OperationalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='mastersku',
            name='audience_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mastersku',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mastersku',
            name='legacy_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mastersku',
            name='region',
            field=models.CharField(choices=[('u', 'UAE'), ('t', 'Thailand'), ('a', 'All')], default='u', help_text='当前允许推送的市场范围（可修改，与编码中的区域码无关）', max_length=1),
        ),
        migrations.AddField(
            model_name='mastersku',
            name='regular_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='划线原价（展示用）', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='mastersku',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='mastersku',
            name='video_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='mastersku',
            name='master_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='mastersku',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), help_text='实际成交价（利润计算用）', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='mastersku',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='skus', to='pim.category'),
        ),
        migrations.AddField(
            model_name='mastersku',
            name='primary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_skus', to='pim.category'),
        ),
        migrations.CreateModel(
            name='MasterCodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=1)),
                ('category_code', models.CharField(max_length=1)),
                ('last_sequence', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('region', 'category_code')},
            },
        ),
        migrations.AddField(
            model_name='mastersku',
            name='operational_tags',
            field=models.ManyToManyField(blank=True, to='pim.operationaltag'),
        ),
        migrations.AddIndex(
            model_name='mastersku',
            index=models.Index(fields=['master_code'], name='pim_masters_master__fe507b_idx'),
        ),
        migrations.AddIndex(
            model_name='mastersku',
            index=models.Index(fields=['legacy_code'], name='pim_masters_legacy__934fc5_idx'),
        ),
        migrations.AddIndex(
            model_name='mastersku',
            index=models.Index(fields=['region', 'is_active'], name='pim_masters_region_73115f_idx'),
        ),
        migrations.AddField(
            model_name='priceauditlog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='priceauditlog',
            name='master_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_logs', to='pim.mastersku'),
        ),
    ]
