# Generated by Django 5.2.11 on 2026-03-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0009_importbatchalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersku',
            name='title_th',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
