# Generated by Django 5.2.11 on 2026-03-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0010_mastersku_title_th'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocr_enabled', models.BooleanField(default=True, verbose_name='OCR 功能')),
                ('copywriting_enabled', models.BooleanField(default=True, verbose_name='文案优化')),
                ('review_assistant_enabled', models.BooleanField(default=True, verbose_name='审核助手')),
                ('primary_model', models.CharField(choices=[('claude-3-5-haiku-20241022', 'Claude 3.5 Haiku (快/便宜)'), ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet (平衡)'), ('claude-3-opus-20240229', 'Claude 3 Opus (最强/贵)')], default='claude-3-5-haiku-20241022', max_length=50, verbose_name='主模型')),
                ('fallback_model', models.CharField(choices=[('claude-3-5-haiku-20241022', 'Claude 3.5 Haiku (快/便宜)'), ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet (平衡)'), ('claude-3-opus-20240229', 'Claude 3 Opus (最强/贵)')], default='claude-3-5-haiku-20241022', max_length=50, verbose_name='降级模型')),
                ('enable_fallback', models.BooleanField(default=True, verbose_name='启用降级')),
                ('max_retries', models.IntegerField(default=2, verbose_name='最大重试次数')),
                ('timeout_seconds', models.IntegerField(default=30, verbose_name='超时时间 (秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI 配置',
                'verbose_name_plural': 'AI 配置',
            },
        ),
    ]
