# Generated by Django 5.2.11 on 2026-03-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0011_aiconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersku',
            name='ever_published',
            field=models.BooleanField(default=False, help_text='是否曾经上架过'),
        ),
        migrations.AlterField(
            model_name='mastersku',
            name='review_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('publishable', 'Publishable'), ('inactive_delisted', 'Inactive (Delisted)')], db_index=True, default='draft', max_length=20),
        ),
    ]
