# Generated by Django 5.2.11 on 2026-03-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0012_mastersku_ever_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersku',
            name='ai_assisted',
            field=models.CharField(choices=[('none', '完全手动'), ('ocr', 'AI 识别'), ('optimize', 'AI 优化'), ('both', 'AI 生成')], default='none', help_text='AI 辅助程度', max_length=20),
        ),
    ]
