# Generated by Django 5.1 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0014_brand_and_dictionary_active_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='脏词内容')),
                ('category', models.CharField(
                    choices=[
                        ('profanity', 'Profanity/脏话'),
                        ('fraud', 'Fraud/诈骗'),
                        ('contraband', 'Contraband/违禁品'),
                        ('adult', 'Adult/成人内容'),
                        ('political', 'Political/敏感政治'),
                        ('other', 'Other/其他'),
                    ],
                    default='other',
                    max_length=50,
                    verbose_name='脏词分类'
                )),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banned Word',
                'verbose_name_plural': 'Banned Words',
                'ordering': ['word'],
            },
        ),
    ]
