# Generated by Django 5.1 on 2026-03-05

from django.db import migrations


def seed_banned_words(apps, schema_editor):
    BannedWord = apps.get_model('pim', 'BannedWord')
    default_words = [
        {'word': 'fuck', 'category': 'profanity'},
        {'word': 'shit', 'category': 'profanity'},
        {'word': '诈骗', 'category': 'fraud'},
        {'word': '违禁', 'category': 'contraband'},
        {'word': '毒品', 'category': 'contraband'},
    ]
    for item in default_words:
        BannedWord.objects.get_or_create(
            word=item['word'],
            defaults={'category': item['category'], 'is_active': True}
        )


def reverse_seed_banned_words(apps, schema_editor):
    BannedWord = apps.get_model('pim', 'BannedWord')
    BannedWord.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0015_bannedword'),
    ]

    operations = [
        migrations.RunPython(seed_banned_words, reverse_seed_banned_words),
    ]
