# Generated by Django 5.2.11 on 2026-03-02 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pim', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('self_operated', 'Self Operated'), ('distributor', 'Distributor')], default='distributor', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_a', models.CharField(blank=True, default='', max_length=255, verbose_name='Product Domain (A)')),
                ('domain_b', models.CharField(blank=True, default='', max_length=255, verbose_name='White Page Domain (B)')),
                ('pixel_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Facebook Pixel ID')),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=50)),
                ('payment_method', models.CharField(blank=True, default='', max_length=255, verbose_name='Ad Payment Method')),
                ('cloaker_config', models.JSONField(blank=True, default=dict)),
                ('distributor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_environment', to='sites.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='DistributorSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='sites.distributor')),
                ('master_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_selections', to='pim.mastersku')),
            ],
            options={
                'unique_together': {('distributor', 'master_sku')},
            },
        ),
    ]
